version: '3.8'
services:
  svc_auth:
    image: 'authentication_service'
    ports:
      - "${SVC_AUTH_PORT}:80"
    environment:
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_USER=${DB_USER}
      - DATABASE_URL=db_user:5432/users
    networks:
      - userServices
      - authServices
  svc_user:
    image: 'user_service'
    ports:
      - "${SVC_USR_PORT}:80"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_HOST=db_user
      - DB_PORT=5432
      - AUTHENTICATION_SERVER=http://auth_svc:${SVC_AUTH_PORT}/authenticate
    networks:
      - userServices
      - authServices
  svc_chat:
    image: 'chat_service'
    ports:
      - "${SVC_CHAT_PORT}:8080"
    environment:
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_USER=${DB_USER}
      - DATABASE_URL=db_chat:5432/chat
      - AUTHENTICATION_SERVER=http://auth_svc:${SVC_AUTH_PORT}/authenticate
    networks:
      - chatServices
      - authServices
  db_user:
    image: "db_user"
    ports:
      - "${DB_USR_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - userServices
  webapp_frontend:
    image: 'frontend_webapp'
    ports:
      - "${WEBAPP_FRONTEND_PORT}:80"
    networks:
      - frontendWebapp
  db_chat:
    image: "db_chat"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - chatServices
  db_message:
    image: "db_message"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - messageServices

networks:
  userServices:
  chatServices:
  messageServices:
  authServices:
  frontendWebapp:
