version: '3.8'
services:
  svc_auth:
    image: 'authentication_service'
    ports:
      - "81:80"
    environment:
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_USER=${DB_USER}
      - DATABASE_URL=db_user:5432/users
    networks:
      - userServices
  Mimir:
    image: 'mimir'
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/chat_service
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
  db_user:
    image: "db_user"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - userServices
  db_chat:
    image: "db_chat"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - chatServices
  db_message:
    image: "db_message"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - messageServices
  PostgreSQL:
    image: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  userServices:
  chatServices:
  messageServices:
