-- MySQL Script generated by MySQL Workbench
-- Mon Jun 20 13:48:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat_service` DEFAULT CHARACTER SET utf8 ;
USE `chat_service` ;

-- -----------------------------------------------------
-- Table `chat_service`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_service`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_service`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_service`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chat_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_service`.`chatParticipant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_service`.`chatParticipant` (
  `user_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `chat_id`),
  INDEX `fk_chat_idx` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `chat_service`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat`
    FOREIGN KEY (`chat_id`)
    REFERENCES `chat_service`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_service`.`chatMessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_service`.`chatMessage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `chat_id` INT NOT NULL,
  `time` TIMESTAMP NULL,
  `author_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_id_idx` (`chat_id` ASC) VISIBLE,
  INDEX `fk_author_id_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `chat_service`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `chat_service`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
